const path = require('path')
console.log('Название файла: ', path.basename(__filename))
console.log('Имя дериктории: ', path.basename(__dirname))
console.log('Расширение файла', path.extname(__filename))
console.log('Parse:',path.parse(__filename))
console.log('Parse:',path.parse(__filename).name)
console.log(path.join(__dirname,'server','index.html'))